# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21373d1179a02221423d523778f0d6eb949088343d0e8eb89c3c47e4799fdd9633b009b98a914835f94ddea36093bdd43018455f4bb2c4e4fe5a4043f0053d52

test:
  secret_key_base: ac0336b43db7474a2bf37c9fca3daf39a504a1b3604ec0d614dbde994137b9a582017184e593ca9bdec9c1c8136161b2682e22736c72efb7cfc1adfd02a5254b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
